spring.application.name=shifttrack

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shifttrack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shifttrack}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:shifttrack}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080